[colors.primary]
background = '#fdfdfd'
foreground = '#383a42'

[colors.normal]
black   = '#fafafa'
red     = '#ca1243'
green   = '#50a14f'
yellow  = '#c18401'
blue    = '#4078f2'
magenta = '#a626a4'
cyan    = '#0184bc'
white   = '#383a42'

[colors.bright]
black   = '#a0a1a7'
red     = '#ca1243'
green   = '#50a14f'
yellow  = '#c18401'
blue    = '#4078f2'
magenta = '#a626a4'
cyan    = '#0184bc'
white   = '#090a0b'
