[colors.primary]
background = "#002b36"
foreground = "#93a1a1"

[colors.cursor]
text = "#002b36"
cursor = "#93a1a1"

[colors.vi_mode_cursor]
text = "#002b36"
cursor = "#93a1a1"

[colors.search.matches]
foreground = "#002b36"
background = "#fdf6e3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#657b83"
background = "#93a1a1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#002b36"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#6c71c4"
cyan = "#2aa198"
white = "#93a1a1"

[colors.bright]
black = "#657b83"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#6c71c4"
cyan = "#2aa198"
white = "#fdf6e3"

[colors.dim]
black = "#fdf6e3"
red = "#dc322f"
green = "#6c71c4"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#859900"
cyan = "#2aa198"
white = "#657b83"

