general.import = ["~/.config/alacritty/themes/themes/onenord.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
decorations = "full"
opacity = 0.9
padding.x = 5
padding.y = 5

[scrolling]
history = 10000

[font]
normal = { family = "caskaydiacove nf", style = "regular" }
bold = { family = "caskaydiacove NF", style = "bold" }
size = 12

[cursor]
style = { shape = "Beam", blinking = "on" }
