# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package
$character
"""

right_format = """
$cmd_duration
"""

scan_timeout = 10

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
#success_symbol = '[❯](#98c379)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[❯](#996761)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[directory]
truncation_length = 3
