# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
# If you encounter any problems, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]

prepend_keymap = [

	{ on = [ "g", "a" ],      run = "cd ~/Documents/harddrive/anime/",    desc = "cd ~/Documents/harddrive/anime/" },
	{ on = [ "g", "b" ],      run = "cd ~/Pictures/screenshots",          desc = "cd ~/Pictures/screenshots" },
	{ on = [ "g", "c", "d" ], run = "cd ~/Documents/code",                desc = "cd ~/Documents/code" },
	{ on = [ "g", "c", "c" ], run = "cd ~/Videos/clips",                  desc = "cd ~/Videos/clips" },
	{ on = [ "g", "c", "b" ], run = "cd ~/Documents/books/",              desc = "cd ~/Documents/books/" },
	{ on = [ "g", "c", "o" ], run = "cd ~/.config",                       desc = "cd ~/.config" },
	{ on = [ "g", "c", "p" ], run = "cd ~/Pictures/Code",                 desc = "cd ~/Pictures/Code" },
	{ on = [ "g", "c", "n" ], run = "cd ~/Videos/code/neetcodeIO/",       desc = "cd ~/Videos/code/neetcodeIO/" },
	{ on = [ "g", "c", "v" ], run = "cd ~/Videos/code/",                  desc = "cd ~/Videos/code" },
	{ on = [ "g", "d", "d" ], run = "cd ~/Downloads",                     desc = "cd ~/Downloads" },
	{ on = [ "g", "d", "f" ], run = "cd ~/Documents",                     desc = "cd ~/Documents" },
	{ on = [ "g", "d", "c" ], run = "cd ~/Documents/code",                desc = "cd ~/Documents" },
	{ on = [ "g", "f"],       run = "cd ~/Documents/flash",               desc = "cd ~/Documents/flash" },
	{ on = [ "g", "e"],       run = "cd ~/Documents/harddrive",           desc = "cd ~/Documents/harddrive" },
	{ on = [ "g", "k"],       run = "cd ~/Documents/konkour",             desc = "cd ~/Documents/konkour" },
	{ on = [ "g", "l"],       run = "cd ~/.local",                        desc = "cd ~/.local" },
	{ on = [ "g", "m"],       run = "cd ~/Music",                         desc = "cd ~/Music" },
	{ on = [ "g", "p"],       run = "cd ~/Documents/phone",               desc = "cd ~/Documents/phone" },
	{ on = [ "g", "v"],       run = "cd ~/Videos",                        desc = "cd ~/Videos" },
	{ on = [ "g", "w"],       run = "cd ~/Pictures/wallpapers",           desc = "cd ~/Pictures/wallpapers" },
	{ on = [ "g", "y"],       run = "cd ~/Videos/youtube",                desc = "cd ~/Videos/youtube" },
	{ on = [ "g", "s"],       run = "cd ~/Videos/screencaps",             desc = "cd ~/Videos/screencaps" },
	{ on = [ "g", "t"],       run = "cd '~/Downloads/Telegram Desktop/'", desc = "cd ~/Downloads/Telegram Desktop" },


# quality of life
	{ on = "<C-c>",         run = ['shell -- for path in %s; do echo "file://$path"; done | xclip -i -sel c -t text/uri-list', "escape"]},
	{ on = "`",             run = 'shell zsh --block',                          desc = "Open an interactive shell" },
	{ on = "d",             run = "yank --cut",                                 desc = "Yank selected files (cut)" },
	{ on = [ "g", "r" ],    run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "cd git root" },
	{ on = [ "m", "e" ],    run = "shell -- magick %s -append ~/merged.jpg",    desc = "append images" },
	{ on = [ "s", "f" ],    run = "search --via=fd",                            desc = "Search files by name using fd" },
	{ on = [ "s", "r" ],    run = "search --via=rg",                            desc = "Search files by content using ripgrep" },
	{ on = [ "s", "w" ],    run = 'shell -- wallpaper.sh "$1"',                 desc = "Set new wallpaper" },

# plugin bindings
	{ on = "<Right>",    run = "plugin smart-enter",          desc = "Enter the child directory, or open the file" },
	{ on = "M",          run = "plugin mount",                desc = "open mount menu" },
	{ on = "l",          run = "plugin smart-enter",          desc = "Enter the child directory, or open the file" },
	{ on = [ "c", "C" ], run = "plugin copy-file-contents",   desc = "Copy file contents" },
	{ on = [ "c", "m" ], run = "plugin chmod",                desc = "chmod selected files" },
	{ on = ["g","o"],    run = "plugin lazygit",              desc = "open lazygit"},
  { on = "u",          run = "plugin restore",              desc = "Restore last deleted files/folders" },
  { on = [ "C" ],      run = "plugin ouch",                 desc = "compress with ouch(format is detected based on file extension)" },

]

# [tasks]
# prepend_keymap = []
#
# [pick]
# prepend_keymap = []
#
# [input]
# prepend_keymap = []
